//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormService.ServiceMath {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMath.ICulcService")]
    public interface ICulcService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICulcService/Add", ReplyAction="http://tempuri.org/ICulcService/AddResponse")]
        int Add(int param1, int param2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICulcService/Add", ReplyAction="http://tempuri.org/ICulcService/AddResponse")]
        System.Threading.Tasks.Task<int> AddAsync(int param1, int param2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICulcServiceChannel : WinFormService.ServiceMath.ICulcService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CulcServiceClient : System.ServiceModel.ClientBase<WinFormService.ServiceMath.ICulcService>, WinFormService.ServiceMath.ICulcService {
        
        public CulcServiceClient() {
        }
        
        public CulcServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CulcServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CulcServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CulcServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(int param1, int param2) {
            return base.Channel.Add(param1, param2);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int param1, int param2) {
            return base.Channel.AddAsync(param1, param2);
        }
    }
}
